resolver: lts-18.13

packages:
- .

extra-deps:
- discord-haskell-1.12.5
- stm-containers-1.2
- stm-hamt-1.2.0.7
- emoji-0.1.0.2
- git: https://github.com/yutotakano/opus.git
  commit: ace2ef14109b4cdbec74cfd5606f27261854b210
