resolver: lts-18.24

packages:
- .

extra-deps:
- discord-haskell-1.14.0
- stm-containers-1.2
- stm-hamt-1.2.0.7
- emoji-0.1.0.2
- microlens-0.4.13.0
- microlens-th-0.4.3.10
- git: https://github.com/yutotakano/opus.git
  commit: 8ba5739821af9c27cf9d50f03b72b58ed88b913a
